### ISSUE TITLE
Can I takeover via Oracle Eloqua?

### ISSUE THREAD

**Issue by glasscannonbuild** [EdOverflow/can-i-take-over-xyz#120]
I've come across a CNAME pointing to s1786589854.t.en25.com domain that should correspond to oracle eloqua. How does one register a such domain?

![elt](https://user-images.githubusercontent.com/49520104/67722253-eadb3f00-f9d8-11e9-83e6-f4e2918f601b.png)

**Comment by riramar** [comment]
I've asked them about Oracle Cloud service (custhelp.com subdomains) and that's what I got back:

> Thank you for reporting this to us and for your patience. It is not
possible for cloud customers to create subdomains under the custhelp.com
or oracle.com domains. Customers which require them are allocated
subdomains by Oracle when their service begins, and they cannot
arbitrarily change it afterwards.

Not sure if would be the same case for en25.com subdomains but if you want to try I've contacted them true this email secalert_us@oracle.com.

**Comment by bcoles** [comment]
I'm not sure about "Site Not Found", but other generic error messages (below) do not mean that the CNAME record for the subdomain is dangling.

![image](https://user-images.githubusercontent.com/434827/181161174-443841fe-36ad-4760-a2bc-7cecc48962ae.png)

![image](https://user-images.githubusercontent.com/434827/181161194-6b0acdf1-8761-4c26-8bb8-98d92d227e62.png)

These are generic error messages presented on `*.en25.com` and `*.hs.eloqua.com` landing pages when browsing to the web server root path. Content on these services requires specifying the correct URL path.

You can often find existing content on these domains in search engines, then check for this content to see whether the instance is still registered.

For example, if DNS records for `example.domain.local` pointed to `1786589854.t.en25.com`, search google for `"example.domain.local"` and `site:example.domain.local`. The search results may include valid URLs for this subdomain, demonstrating that the subdomain is in use and that the DNS record is not a dangling CNAME.

Pages which do not exist (although still return 200 OK) may display a similar error message to the screenshot shown in OP.

![image](https://user-images.githubusercontent.com/434827/181162377-d523b67d-1cc2-4dfc-837e-88e1e46314a3.png)

This error page is identical to the screenshot in OP, but does not display "Site Not Found". It is possible that Oracle have changed the error page to no longer display "Site Not Found" since the OP in 2019.
