### ISSUE TITLE
Short.io takeover

### ISSUE THREAD

**Issue by pdelteil** [EdOverflow/can-i-take-over-xyz#260]
## Service name 

Short.io

## Proof

![Screenshot from 2022-02-15 15-30-57](https://user-images.githubusercontent.com/20244863/154144202-bd394113-dddf-4f37-949b-396c4cd98f5a.png)

```
dig target.tld

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52054
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;target.tld.		IN	A

;; ANSWER SECTION:
target.tld.	3600	IN	A	52.21.33.16
target.tld.	3600	IN	A	52.2.56.64

```

## Documentation

https://help.short.io/en/articles/4065825-general-subdomain-setup-instruction

**Comment by pdelteil** [comment]
I also added this [template](https://github.com/projectdiscovery/nuclei-templates/blob/master/takeovers/short-io.yaml) to nuclei.

**Comment by gugu** [comment]
Hi!

Thanks for checking for domain takeover - we are aware of this type of attack and prevent it from happening.

I'll share our checks:
1. If you connect a domain example.com to Short.io, noone can add example.com subdomain except you
2. You can not delete a domain in our system if it is still marked as configured. We require to disconnect the domain first. It is annoying for our users, but we take security seriously

There can be a corner case when user points DNS records to our IP and does not add a domain, but should be a deliberate action because we display configuration instruction after the user adds a domain in our system.

Also, there can be a corner case when a user adds a domain he does not control, but it does not pose a security risk, only prevents legitimate domain owner from using our service (and this problem is solved by our support engineers).

Feel free to tell us if you don't think these measures are enough

**Comment by 0xspade** [comment]
> Hi!
> 
> Thanks for checking for domain takeover - we are aware of this type of attack and prevent it from happening.
> 
> I'll share our checks:
> 
>     1. If you connect a domain example.com to Short.io, noone can add example.com subdomain except you
> 
>     2. You can not delete a domain in our system if it is still marked as configured. We require to disconnect the domain first. It is annoying for our users, but we take security seriously
> 
> 
> There can be a corner case when user points DNS records to our IP and does not add a domain, but should be a deliberate action because we display configuration instruction after the user adds a domain in our system.
>
> Also, there can be a corner case when a user adds a domain he does not control, but it does not pose a security risk, only prevents legitimate domain owner from using our service (and this problem is solved by our support engineers).
> 
> Feel free to tell us if you don't think these measures are enough

confirm, not vulnerable anymore.

**Comment by gugu** [comment]
Can you please update the Readme?

**Comment by pdelteil** [comment]
Hello there gugu, 

I can confirm this takeover is still possible.

**Comment by hlynurfrey001** [comment]
> Hello there @gugu,
> 
> I can confirm this takeover is still possible.

How ??

**Comment by gugu** [comment]
Yes, more details will be helpful addition to your answer

**Comment by pdelteil** [comment]
> > Hello there @gugu,
> > I can confirm this takeover is still possible.
> 
> How ??

Adding a custom domain discovered with the template. Test it yourself.

**Comment by pdelteil** [comment]
> Yes, more details will be helpful addition to your answer

where can I send you a report? BBH? 🤣

**Comment by hlynurfrey001** [comment]
> > Yes, more details will be helpful addition to your answer
> 
> where can I send you a report? BBH? 🤣

At mail hlynurfrey@gmail.com

**Comment by hlynurfrey001** [comment]
> a custom domain discovered with the template. Test it you

what do you mean ?

**Comment by samogod** [comment]
![image](https://github.com/user-attachments/assets/8d096926-3d7f-414b-a837-9a0715d54d2b)


Could you give steps for PoC? @pdelteil
