### ISSUE TITLE
A simple opinion.

### ISSUE THREAD

**Issue by oldesec** [EdOverflow/can-i-take-over-xyz#84]
Hi.

I think it is good to mark "time" in the template.

Example) "Kinsta" service was added. But when?

So, I think it would be nice to add "time" to the "All entries" table.

By doing so, the newly added service can be confirmed intuitively.

Thanks.

**Comment by Avileox** [comment]
Thank you for your opinion but most of the services have a reference issue where issue contains information like time and other details about the takeover.

**Comment by EdOverflow** [comment]
Hi @oldesec,

Thank you very much for your feedback. I am currently working on redesigning this project entirely because I am not convinced that GitHub is the best medium for maintaining a list like this. A redesign should hopefully resolve the issue concerning including dates associated with entries.
